apiVersion: v1
kind: Service
metadata:
  name: inference-svc
  namespace: inference
  labels:
    app: inference-service
spec:
  type: NodePort
  selector:
    app: inference-service
  ports:
    - name: http
      port: 8002          # cluster-internal port
      targetPort: 8002    # pod container port
      nodePort: 30092     # must match kind-config.yaml extraPortMappings containerPort
